services:
  postgres-order-db:
    image: postgres:15-alpine
    container_name: order-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:5434"

  order-service-app:
    container_name: order-service-app
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_PORT: ${APP_PORT}
      DB_NAME: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      postgres-order-db:
        condition: service_started